# Generated by Django 2.2.5 on 2020-08-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about',
            field=models.CharField(default='null', max_length=101),
        ),
    ]
